language: python
python:
    - "nightly"
    - '3.6-dev'
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
install:
  - |
    # install pip 10 on python 3.3
    # to get requires_python support
    if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then
      pip install pip==10.*
    fi
  - pip install --upgrade setuptools pip
  - pip install --upgrade --pre -e .[test] pytest-cov pytest-warnings codecov
script:
  - py.test --cov jupyter_client jupyter_client
after_success:
  - codecov
matrix:
    allow_failures:
        - python: nightly
branches:
  except:
    - /^auto-backport-of-pr-[0-9]+$/
